"""Realistic synthetic incident history for a fictional payments company (Northwind Pay)."""
from datetime import datetime

INCIDENTS = [
 dict(id="INC-2011", date=datetime(2026, 3, 4), service="payments-api",
  title="Checkout timeouts after deploy v2.11.0",
  symptoms="p99 latency jumped to 9s, HTTP 504s from checkout-web, logs full of 'QueuePool limit of size 20 overflow 10 reached' starting 7 minutes after deploy.",
  root_cause="A new refund endpoint opened a DB session and never closed it on the error path, leaking connections until the pool was exhausted.",
  resolution="Rolled back to v2.10.4, then restarted pgbouncer to clear leaked server connections. Hotfix added a context manager around the session.",
  failed="Scaling payments-api from 6 to 20 pods made it worse - more pods meant more leaked connections and Postgres hit max_connections. Wasted 35 minutes.",
  ttr_minutes=62, engineer="Meera R."),
 dict(id="INC-2019", date=datetime(2026, 3, 19), service="redis-cache",
  title="Cache stampede on product-catalog after nightly flush",
  symptoms="catalog-service latency 6x, Postgres CPU at 95%, redis hit ratio dropped from 96% to 12% at 00:05 UTC.",
  root_cause="All catalog keys were written with an identical 24h TTL, so they expired together and every request fell through to Postgres.",
  resolution="Warmed the cache with the top 5k SKUs, then added +/-15% random jitter to TTLs and request coalescing (single-flight) on cache miss.",
  failed="Increasing Redis maxmemory did nothing - memory was not the problem.",
  ttr_minutes=48, engineer="Arjun P."),
 dict(id="INC-2026", date=datetime(2026, 4, 2), service="kafka",
  title="Settlement consumer lag growing unbounded",
  symptoms="consumer group settlement-writer lag grew to 2.4M messages, no errors in the dashboard, partition 3 stuck at one offset.",
  root_cause="A poison-pill message with a malformed currency field crashed the consumer on every retry on partition 3.",
  resolution="Skipped the offending offset, routed it to the dead-letter topic, and added schema validation with a DLQ in the consumer.",
  failed="Adding more consumers did not help because only one consumer owns partition 3. Restarting the group just replayed the crash.",
  ttr_minutes=55, engineer="Sana K."),
 dict(id="INC-2031", date=datetime(2026, 4, 17), service="payments-api",
  title="Connection pool exhaustion after deploy v2.14.2",
  symptoms="504s on /v1/charge, 'remaining connection slots are reserved for non-replication superuser connections' from Postgres, started 5 minutes after deploy.",
  root_cause="Long-running analytics query added in the deploy held connections open; combined with the pool size of 20 per pod this saturated max_connections.",
  resolution="Rolled back immediately (4 min), then moved the analytics query to the read replica and set statement_timeout=5s on the primary.",
  failed="Restarting pods only bought 3 minutes. Scaling pods was NOT tried this time because of INC-2011 - which saved time.",
  ttr_minutes=19, engineer="Meera R."),
 dict(id="INC-2038", date=datetime(2026, 5, 6), service="auth-service",
  title="Mass login failures - expired internal TLS certificate",
  symptoms="401/502 for all logins, 'x509: certificate has expired' in auth-service to user-db logs, began exactly at 03:00 UTC.",
  root_cause="Internal CA-issued cert for the user-db mTLS link expired; the renewal cron had been silently failing for 3 weeks.",
  resolution="Manually reissued the cert via the internal CA, rolled the pods, and added a 14-day expiry alert plus a heartbeat on the renewal job.",
  failed="Checking application code and redeploying the previous version - the error was unrelated to code.",
  ttr_minutes=41, engineer="Ravi T."),
 dict(id="INC-2044", date=datetime(2026, 5, 22), service="payments-api",
  title="Latency spike after deploy v2.16.0 - pool exhaustion again",
  symptoms="p99 latency 8s, 'QueuePool limit of size 20 overflow 10 reached', began 6 minutes post-deploy, Postgres connections at 98% of max.",
  root_cause="New webhook retry worker checked out connections and held them during outbound HTTP calls to slow merchant endpoints.",
  resolution="Rolled back to v2.15.3 in 5 minutes. Fixed by releasing the DB connection before the outbound HTTP call.",
  failed="On-call initially tried increasing pool size to 40 - that only moved the failure point and raised Postgres load.",
  ttr_minutes=23, engineer="Arjun P."),
 dict(id="INC-2052", date=datetime(2026, 6, 9), service="checkout-web",
  title="Checkout 500s from CDN misconfiguration",
  symptoms="Static bundle 404 for 8% of users, mixed asset hashes in browser console, started right after frontend deploy.",
  root_cause="CDN cache served a stale index.html referencing old asset hashes that were purged from the origin.",
  resolution="Invalidated /index.html on the CDN and kept previous asset versions in the origin for 24h going forward.",
  failed="Rolling back the frontend deploy - it re-published the same conflict.",
  ttr_minutes=27, engineer="Sana K."),
 dict(id="INC-2060", date=datetime(2026, 6, 25), service="postgres-primary",
  title="Replication lag on read replica after bulk backfill",
  symptoms="Replica lag 14 minutes, stale balances shown in dashboard, WAL disk usage growing.",
  root_cause="A 40M-row backfill ran in one transaction, producing a giant WAL burst that the replica could not replay.",
  resolution="Paused the backfill, let the replica catch up, then re-ran it in 50k-row batches with sleeps.",
  failed="Restarting the replica forced a longer catch-up.",
  ttr_minutes=90, engineer="Ravi T."),
 dict(id="INC-2071", date=datetime(2026, 7, 14), service="kafka",
  title="Notification consumer lag - poison pill again",
  symptoms="notification-sender lag rising, single partition stuck, same offset retried in a loop.",
  root_cause="Malformed template payload crashed the consumer; the DLQ from INC-2026 was not yet applied to this service.",
  resolution="Skipped the offset, sent it to the DLQ, and rolled the settlement DLQ wrapper out to every consumer service.",
  failed="Nothing wasted - the on-call recognised the pattern from INC-2026 and went straight to the stuck partition.",
  ttr_minutes=14, engineer="Sana K."),
 dict(id="INC-2079", date=datetime(2026, 8, 3), service="redis-cache",
  title="Session cache latency after Redis failover",
  symptoms="Random 2-3s login latency for 10 minutes after the Redis primary failed over to the replica.",
  root_cause="Clients kept stale DNS for the old primary; the connection pool retried with a 2s timeout before reconnecting.",
  resolution="Reduced client DNS TTL caching, lowered connect timeout to 300ms and enabled pool health checks.",
  failed="Restarting Redis - it triggered a second failover.",
  ttr_minutes=33, engineer="Arjun P."),
 dict(id="INC-2088", date=datetime(2026, 8, 27), service="payments-api",
  title="Pool exhaustion on v2.18.1 - agent-assisted",
  symptoms="504s and 'QueuePool limit' errors 6 minutes post-deploy, Postgres connections near max.",
  root_cause="Pattern repeat: a new batch-export feature held sessions open across a slow S3 upload.",
  resolution="Rolled back within 3 minutes based on the pattern, then fixed the session scope.",
  failed="Nothing wasted.",
  agent_feedback="helpful - correctly recommended immediate rollback and warned against scaling pods or raising pool size",
  ttr_minutes=9, engineer="Meera R."),
]

# The alert used in the live demo (a NEW incident the agent has never seen)
DEMO_ALERT = """[FIRING] payments-api p99 latency > 8s (threshold 1.5s)
Service: payments-api  |  Deploy: v2.19.0 rolled out 6 minutes ago
checkout-web reporting HTTP 504 on POST /v1/charge (23% of requests)
Log sample: sqlalchemy.exc.TimeoutError: QueuePool limit of size 20 overflow 10 reached, connection timed out, timeout 30.00
Postgres: connections 97/100. CPU normal. Pods: 6/6 healthy."""
